@props([
    'trangChu' => null,
    'ngoiAmDuongs' => null,
    'ngoiHais' => null,
    'gachHoas' => null,
    'about' => null,
    'factory' => null,
    'showroomImages' => null,
    'showroomContent' => null,
    'news' => null,
    'article' => null,
    'articles' => null,
    'relatedArticles' => null,
    'historyArticles' => null,
    'projects' => null,
    'project' => null,
    'relatedProjects' => null,
    'categories' => null,
    'selectedCategory' => null,
    'currentCategory' => null,
    'config' => null,
    'products' => null,
    'relatedProducts' => null,
    'product' => null,
    'colors' => null,
    'dinhMuc' => null,
    'giaTriVuotTroi' => null,
    'parentConfig' => null,
    'pageLabel' => null,
    'indexRouteName' => null,
    'categoryType' => null,
    'categoryLabel' => null,
    'denGomProducts' => null,
    'denSuProducts' => null,
    'featuredProducts' => null,
    'collectionProducts' => null,
    'ngheProducts' => null,
    'linhVatProducts' => null,
    'bgImage' => null,
    'activeOrder' => false,
    'activeAccount' => false,
    'activeCatalog' => false,
    'activeGuide' => false,
    'activeProcess' => false,
    'activePrivacy' => false,
    'activeReturn' => false,
    'activeShipping' => false,
    'image' => null,
    'label1' => null,
    'rate1' => null,
    'label2' => null,
    'rate2' => null,
    'sectionId' => null,
    'sectionClass' => null,
    'sectionTitle' => null,
    'desktopLinkHref' => null,
    'detailRouteName' => null,
    'wrapperClass' => null,
    'titleClass' => null,
    'title' => null,
    'subtitle' => null,
    'description' => null,
    'items' => null,])
<div class="flex-1 lg:pl-12">
  <h1 class="text-[30px] lg:text-[36px] font-arima font-medium text-primary mb-4 lg:mb-10 mt-[-6px]">Quy trình đặt hàng</h1>

  <div class="py-2 lg:py-4">
    <!-- Desktop Image -->
    <img src="{{ asset('assets/images/quy-trinh-dat-hang.svg') }}" alt="Quy trình đặt hàng Thanh Hải Ceramics" class="hidden lg:block w-full h-auto pointer-events-none select-none">
    <!-- Mobile Image -->
    <img src="{{ asset('assets/images/quy-trinh-dat-hang-mobile.svg') }}" alt="Quy trình đặt hàng Thanh Hải Ceramics" class="block lg:hidden w-full h-auto pointer-events-none select-none">
  </div>
</div>